@startuml sequence diagram
!pragma teoz true

skinparam NoteTextAlignment center

actor "3rd party\nattester"

== Initialization ==

note over "fTPM TA": Triggered only once\nat any first interaction\nwith fTPM

"fTPM TA" -> "RA PTA" ++: Hash me

"RA PTA" -> "fTPM TA": Read memory
"RA PTA" -> "RA PTA": Hash fTPM memory
"fTPM TA" <-- "RA PTA" --: fTPM hash

' Formula (2) from https://trustedcomputinggroup.org/wp-content/uploads/Hardware-Requirements-for-Device-Identifier-Composition-Engine-r78_For-Publication.pdf
"fTPM TA" -> "fTPM TA": EPS = HMAC(CDI, "EPS")
"fTPM TA" -> "fTPM TA": Inject EPS

"fTPM TA" -> "fTPM TA": Generate EK with\nTPM2_CreatePrimary
"fTPM TA" -> "fTPM TA": Create EKCert with EKPub as subject\nsigned by OP-TEE private key\ncontaining the hash of the fTPM TA


== Attestation process ==

"3rd party\nattester" -> "User space\napplication" ++: PCR list + Nonce

"User space\napplication" -> "fTPM TA" ++: Forward
"User space\napplication" <-- "fTPM TA" --: Evidence =\nQuote signed by EKpriv,\n[event log],\nDice Cert chain incl. EKCert
"3rd party\nattester" <-- "User space\napplication" --: Evidence

"3rd party\nattester" -> "3rd party\nattester": Make security decision\nregarding own policy\nbased on provided evidence

box "Prover"
    box "Normal World\n        (Linux)" #Salmon
    participant "User space\napplication"
    participant "User space\napplication"
    end box

    box "Secure World (OP-TEE)" #LightBlue
    participant "fTPM TA"
    participant "RA PTA"
    end box
end box

@enduml
